using InRiver.Rest.Lib.Client;
using InRiver.Rest.Lib.Model;

namespace InRiver.Rest.Lib.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IQueryApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Search for entity id&#39;s
        /// </summary>
        /// <remarks>
        /// Available system criterion types and their supported operators&lt;br /&gt;   - -- --  &lt;b&gt;FieldSetId&lt;/b&gt;:(string) Equal, NotEqual, IsEmpty, IsNotEmpty&lt;br /&gt;&lt;b&gt;SegmentIds&lt;/b&gt;:(Integer array) ContainsAny, NotContainsAny&lt;br /&gt;&lt;b&gt;CreatedBy&lt;/b&gt;:(email, string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;ModifiedBy&lt;/b&gt;:(email, string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;Created&lt;/b&gt;:(DateTime) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;LastModified&lt;/b&gt;:(DateTime) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;EntityTypeId&lt;/b&gt;:(string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;Completeness&lt;/b&gt;:(Integer) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;ChannelId&lt;/b&gt;:(Integer) Equal&lt;br /&gt;&lt;b&gt;PublicationId&lt;/b&gt;:(Integer) Equal                Operators for each field datatype in dataCriteria&lt;br /&gt;   - -- --  &lt;b&gt;String&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;LocaleString&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;Boolean&lt;/b&gt;: IsTrue, IsFalse, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;CVL(singlevalue)&lt;/b&gt;: Equal, NotEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;CVL(multivalue)&lt;/b&gt;: ContainsAll, ContainsAny, NotContainsAll, NotContainsAny, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Date time&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Integer and Double&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Xml&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;File&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,                Language  - -- --  &lt;b&gt;LocaleString&lt;/b&gt; is the only data type that supports language.                 Link Criterion&lt;br /&gt;   - -- --  Direction determines if the source or target entity of the link will be included in the result.&lt;br /&gt;  - If direction is \&quot;outbound\&quot;, the link source entity is included in the result&lt;br /&gt;  - If direction is \&quot;inbound\&quot;, the link target entity is included in the result&lt;br /&gt;    If linkCriterion.dataCriteria is omitted the search will simply check if a link exists.&lt;br /&gt;    The boolean linkExists defaults to true and may be omitted. Setting linkExists to false searches for entities without links and can&#39;t be combined with data criteria(in the link criterion).&lt;br /&gt;    Note: Keep your queries as simple as possible. More complex queries take longer time to perform.&lt;br /&gt;
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="queryModel"></param>
        /// <returns>EntityListModel</returns>
        EntityListModel Query(QueryModel queryModel);

        /// <summary>
        /// Search for entity id&#39;s
        /// </summary>
        /// <remarks>
        /// Available system criterion types and their supported operators&lt;br /&gt;   - -- --  &lt;b&gt;FieldSetId&lt;/b&gt;:(string) Equal, NotEqual, IsEmpty, IsNotEmpty&lt;br /&gt;&lt;b&gt;SegmentIds&lt;/b&gt;:(Integer array) ContainsAny, NotContainsAny&lt;br /&gt;&lt;b&gt;CreatedBy&lt;/b&gt;:(email, string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;ModifiedBy&lt;/b&gt;:(email, string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;Created&lt;/b&gt;:(DateTime) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;LastModified&lt;/b&gt;:(DateTime) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;EntityTypeId&lt;/b&gt;:(string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;Completeness&lt;/b&gt;:(Integer) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;ChannelId&lt;/b&gt;:(Integer) Equal&lt;br /&gt;&lt;b&gt;PublicationId&lt;/b&gt;:(Integer) Equal                Operators for each field datatype in dataCriteria&lt;br /&gt;   - -- --  &lt;b&gt;String&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;LocaleString&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;Boolean&lt;/b&gt;: IsTrue, IsFalse, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;CVL(singlevalue)&lt;/b&gt;: Equal, NotEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;CVL(multivalue)&lt;/b&gt;: ContainsAll, ContainsAny, NotContainsAll, NotContainsAny, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Date time&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Integer and Double&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Xml&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;File&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,                Language  - -- --  &lt;b&gt;LocaleString&lt;/b&gt; is the only data type that supports language.                 Link Criterion&lt;br /&gt;   - -- --  Direction determines if the source or target entity of the link will be included in the result.&lt;br /&gt;  - If direction is \&quot;outbound\&quot;, the link source entity is included in the result&lt;br /&gt;  - If direction is \&quot;inbound\&quot;, the link target entity is included in the result&lt;br /&gt;    If linkCriterion.dataCriteria is omitted the search will simply check if a link exists.&lt;br /&gt;    The boolean linkExists defaults to true and may be omitted. Setting linkExists to false searches for entities without links and can&#39;t be combined with data criteria(in the link criterion).&lt;br /&gt;    Note: Keep your queries as simple as possible. More complex queries take longer time to perform.&lt;br /&gt;
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="queryModel"></param>
        /// <returns>ApiResponse of EntityListModel</returns>
        ApiResponse<EntityListModel> QueryWithHttpInfo(QueryModel queryModel);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Search for entity id&#39;s
        /// </summary>
        /// <remarks>
        /// Available system criterion types and their supported operators&lt;br /&gt;   - -- --  &lt;b&gt;FieldSetId&lt;/b&gt;:(string) Equal, NotEqual, IsEmpty, IsNotEmpty&lt;br /&gt;&lt;b&gt;SegmentIds&lt;/b&gt;:(Integer array) ContainsAny, NotContainsAny&lt;br /&gt;&lt;b&gt;CreatedBy&lt;/b&gt;:(email, string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;ModifiedBy&lt;/b&gt;:(email, string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;Created&lt;/b&gt;:(DateTime) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;LastModified&lt;/b&gt;:(DateTime) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;EntityTypeId&lt;/b&gt;:(string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;Completeness&lt;/b&gt;:(Integer) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;ChannelId&lt;/b&gt;:(Integer) Equal&lt;br /&gt;&lt;b&gt;PublicationId&lt;/b&gt;:(Integer) Equal                Operators for each field datatype in dataCriteria&lt;br /&gt;   - -- --  &lt;b&gt;String&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;LocaleString&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;Boolean&lt;/b&gt;: IsTrue, IsFalse, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;CVL(singlevalue)&lt;/b&gt;: Equal, NotEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;CVL(multivalue)&lt;/b&gt;: ContainsAll, ContainsAny, NotContainsAll, NotContainsAny, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Date time&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Integer and Double&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Xml&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;File&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,                Language  - -- --  &lt;b&gt;LocaleString&lt;/b&gt; is the only data type that supports language.                 Link Criterion&lt;br /&gt;   - -- --  Direction determines if the source or target entity of the link will be included in the result.&lt;br /&gt;  - If direction is \&quot;outbound\&quot;, the link source entity is included in the result&lt;br /&gt;  - If direction is \&quot;inbound\&quot;, the link target entity is included in the result&lt;br /&gt;    If linkCriterion.dataCriteria is omitted the search will simply check if a link exists.&lt;br /&gt;    The boolean linkExists defaults to true and may be omitted. Setting linkExists to false searches for entities without links and can&#39;t be combined with data criteria(in the link criterion).&lt;br /&gt;    Note: Keep your queries as simple as possible. More complex queries take longer time to perform.&lt;br /&gt;
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="queryModel"></param>
        /// <returns>Task of EntityListModel</returns>
        System.Threading.Tasks.Task<EntityListModel> QueryAsync(QueryModel queryModel);

        /// <summary>
        /// Search for entity id&#39;s
        /// </summary>
        /// <remarks>
        /// Available system criterion types and their supported operators&lt;br /&gt;   - -- --  &lt;b&gt;FieldSetId&lt;/b&gt;:(string) Equal, NotEqual, IsEmpty, IsNotEmpty&lt;br /&gt;&lt;b&gt;SegmentIds&lt;/b&gt;:(Integer array) ContainsAny, NotContainsAny&lt;br /&gt;&lt;b&gt;CreatedBy&lt;/b&gt;:(email, string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;ModifiedBy&lt;/b&gt;:(email, string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;Created&lt;/b&gt;:(DateTime) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;LastModified&lt;/b&gt;:(DateTime) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;EntityTypeId&lt;/b&gt;:(string) Equal, NotEqual&lt;br /&gt;&lt;b&gt;Completeness&lt;/b&gt;:(Integer) Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual&lt;br /&gt;&lt;b&gt;ChannelId&lt;/b&gt;:(Integer) Equal&lt;br /&gt;&lt;b&gt;PublicationId&lt;/b&gt;:(Integer) Equal                Operators for each field datatype in dataCriteria&lt;br /&gt;   - -- --  &lt;b&gt;String&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;LocaleString&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;Boolean&lt;/b&gt;: IsTrue, IsFalse, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;CVL(singlevalue)&lt;/b&gt;: Equal, NotEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;CVL(multivalue)&lt;/b&gt;: ContainsAll, ContainsAny, NotContainsAll, NotContainsAny, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Date time&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Integer and Double&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,&lt;br /&gt;&lt;b&gt;Xml&lt;/b&gt;: Equal, NotEqual, BeginsWith, IsEmpty, IsNotEmpty, Contains&lt;br /&gt;&lt;b&gt;File&lt;/b&gt;: Equal, NotEqual, GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual, IsEmpty IsNotEmpty,                Language  - -- --  &lt;b&gt;LocaleString&lt;/b&gt; is the only data type that supports language.                 Link Criterion&lt;br /&gt;   - -- --  Direction determines if the source or target entity of the link will be included in the result.&lt;br /&gt;  - If direction is \&quot;outbound\&quot;, the link source entity is included in the result&lt;br /&gt;  - If direction is \&quot;inbound\&quot;, the link target entity is included in the result&lt;br /&gt;    If linkCriterion.dataCriteria is omitted the search will simply check if a link exists.&lt;br /&gt;    The boolean linkExists defaults to true and may be omitted. Setting linkExists to false searches for entities without links and can&#39;t be combined with data criteria(in the link criterion).&lt;br /&gt;    Note: Keep your queries as simple as possible. More complex queries take longer time to perform.&lt;br /&gt;
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="queryModel"></param>
        /// <returns>Task of ApiResponse(EntityListModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<EntityListModel>> QueryAsyncWithHttpInfo(QueryModel queryModel);
        #endregion Asynchronous Operations
    }
}