on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} ./src/InRiver.Rest.Lib/InRiver.Rest.Lib.csproj
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} ./src/InRiver.Rest.Lib/InRiver.Rest.Lib.csproj --no-build --output .
    - name: Push
      run: dotnet nuget push inRiverCommunity.Rest.Client.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}