name: publish to nuget
on: ["push"]
  # push:
  #   branches:
  #     - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/InRiver.Rest.Lib/InRiver.Rest.Lib.csproj
          PACKAGE_NAME: inRiverCommunity.Rest.Client
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}